# Generated by Django 5.2.11 on 2026-08-16 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0010_alter_job_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive custom reports will not appear to employees or be selectable for jobs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Report Template',
                'verbose_name_plural': 'Custom Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomReportField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('date', 'Date'), ('time', 'Time'), ('file', 'File Upload')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/multi-select fields.')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('helper_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_reports.customreporttemplate')),
            ],
            options={
                'verbose_name': 'Custom Report Field',
                'verbose_name_plural': 'Custom Report Fields',
                'ordering': ['order', 'created_at'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CustomReportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_report_submissions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_report_submissions', to='jobs.job')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='custom_reports.customreporttemplate')),
            ],
            options={
                'verbose_name': 'Custom Report Submission',
                'verbose_name_plural': 'Custom Report Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('job', 'template', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='CustomReportResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='custom_reports/uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='custom_reports.customreportfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='custom_reports.customreportsubmission')),
            ],
            options={
                'verbose_name': 'Custom Report Response',
                'verbose_name_plural': 'Custom Report Responses',
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
