# Generated by Django 5.2.11 on 2026-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobphoto',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobphoto',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='report_template_ids',
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.CharField(choices=[('job_created', 'Job Created'), ('job_assigned', 'Job Assigned'), ('job_started', 'Job Started'), ('technician_en_route', 'Technician En Route'), ('arrived_at_site', 'Arrived at Site'), ('safety_form_submitted', 'Safety Form Submitted'), ('report_submitted', 'Report Submitted'), ('note_added', 'Note Added'), ('file_uploaded', 'File Uploaded'), ('status_changed', 'Status Changed'), ('job_completed', 'Job Completed'), ('job_rescheduled', 'Job Rescheduled')], max_length=30),
        ),
        migrations.DeleteModel(
            name='JobNote',
        ),
        migrations.DeleteModel(
            name='JobPhoto',
        ),
        migrations.DeleteModel(
            name='JobTask',
        ),
    ]
