# Generated by Django 5.2.11 on 2026-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobphoto_job_remove_jobphoto_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pre_overdue_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], editable=False, help_text='Stores the status before the job became overdue, used to restore on reschedule', max_length=20, null=True),
        ),
    ]
