# Generated by Django 5.2.11 on 2026-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='insured_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='insured_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='insured_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='insured_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='site_access_info',
            field=models.TextField(blank=True, help_text='Gate codes, access instructions, entry notes etc.'),
        ),
    ]
