# Generated by Django 5.2.11 on 2026-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_insured_address_job_insured_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pre_overdue_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('pending', 'To be booked'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('to_invoice', 'To Invoice'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency_make_safe', 'Emergency Make Safe'), ('overdue', 'Overdue')], editable=False, help_text='Stores the status before the job became overdue, used to restore on reschedule', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'To be booked'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('to_invoice', 'To Invoice'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency_make_safe', 'Emergency Make Safe'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
