# Generated by Django 5.2.11 on 2026-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_pre_overdue_status_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Expected or actual end time of the job', null=True),
        ),
    ]
