# Generated by Django 5.2.11 on 2026-05-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_end_time_to_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scheduled_datetime',
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notes_chat', to='jobs.job'),
        ),
    ]
