# Generated by Django 5.2.11 on 2026-06-18 13:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_end_time_remove_job_scheduled_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Job Details'),
        ),
    ]
