# Generated by Django 5.2.11 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reports', '0001_initial'),
        ('jobs', '0010_alter_job_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custom_reports',
            field=models.ManyToManyField(blank=True, help_text='Custom report templates required for this job', related_name='jobs', to='custom_reports.customreporttemplate'),
        ),
    ]
