# Generated by Django 5.2.11 on 2026-08-16 00:00

from django.db import migrations, models

import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_custom_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(blank=True, choices=jobs.models.JobPriority.choices, max_length=10, null=True),
        ),
    ]
