# Generated by Django 5.2.11 on 2026-03-12 16:10

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0003_remove_jobphoto_job_remove_jobphoto_uploaded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('roof', 'Roof Report'), ('appliance', 'Appliance Report'), ('drain_inspection', 'Drain Inspection Report'), ('leak_inspection', 'Leak Inspection Report'), ('spray_test', 'Spray Test Report')], max_length=30)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who attached this report type to the job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_reports', to='jobs.job')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Report',
                'verbose_name_plural': 'Job Reports',
                'ordering': ['created_at'],
                'unique_together': {('job', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='DrainInspectionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('attendance_datetime', models.DateTimeField()),
                ('property_construction', models.CharField(blank=True, choices=[('brick_veneer', 'Brick Veneer'), ('double_brick', 'Double Brick')], max_length=20)),
                ('discussion_with_insured', models.TextField(blank=True)),
                ('resultant_damage', models.TextField(blank=True)),
                ('area_of_inspection', models.CharField(blank=True, choices=[('consumer_sewer', 'Consumer Sewer'), ('consumer_stormwater', 'Consumer Stormwater')], max_length=25)),
                ('pipe_construction', models.CharField(blank=True, choices=[('pvc', 'PVC'), ('ceramic', 'Ceramic'), ('hdpe', 'HDPE'), ('galvanised', 'Galvanised'), ('lead', 'Lead')], max_length=15)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drain_reports', to=settings.AUTH_USER_MODEL)),
                ('job_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drain_submission', to='reports.jobreport')),
            ],
            options={
                'verbose_name': 'Drain Inspection Submission',
            },
        ),
        migrations.CreateModel(
            name='ApplianceReportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('attendance_datetime', models.DateTimeField()),
                ('discussion_with_insured', models.TextField(blank=True)),
                ('appliance_brand', models.CharField(blank=True, max_length=150)),
                ('model_no', models.CharField(blank=True, max_length=150)),
                ('approx_age', models.CharField(blank=True, help_text="Approximate age of appliance e.g. '5 years', '~10 yrs'", max_length=50)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliance_reports', to=settings.AUTH_USER_MODEL)),
                ('job_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_submission', to='reports.jobreport')),
            ],
            options={
                'verbose_name': 'Appliance Report Submission',
            },
        ),
        migrations.CreateModel(
            name='LeakInspectionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('attendance_datetime', models.DateTimeField()),
                ('property_construction', models.CharField(blank=True, choices=[('brick_veneer', 'Brick Veneer'), ('double_brick', 'Double Brick')], max_length=20)),
                ('discussion_with_site_contact', models.TextField(blank=True)),
                ('resultant_damage', models.TextField(blank=True)),
                ('testing_location', models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('ensuite', 'Ensuite'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('other', 'Other')], max_length=15)),
                ('pressure_cold_line', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('pressure_hot_line', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('pressure_shower_breech', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('pressure_bath_breech', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('flood_test_shower', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('flood_test_bath', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('spray_test_wall_tiles', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('spray_test_shower_screen', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('tile_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('grout_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('silicone_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('silicone_around_spindles', models.BooleanField(blank=True, help_text='Silicone around spindles and penetrations present?', null=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leak_submission', to='reports.jobreport')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leak_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leak Inspection Submission',
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('photo_type', models.CharField(help_text="What this photo represents. Examples: 'front_of_dwelling', 'damage_photo', 'job_photo', 'test_results', 'spindle_photo', 'whole_area'", max_length=50)),
                ('image', models.ImageField(upload_to=reports.models.report_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoofReportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict, help_text='Snapshot of job/client/employee data at submission time')),
                ('attendance_datetime', models.DateTimeField(help_text='Date and time of attendance on site')),
                ('discussion_with_insured', models.TextField(blank=True)),
                ('type_of_dwelling', models.CharField(blank=True, choices=[('single_story', 'Single Story'), ('two_story', 'Two Story'), ('complex', 'Complex Building')], max_length=20)),
                ('resulting_damages', models.TextField(blank=True)),
                ('leak_fixed_by_insured', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=5)),
                ('type_of_roof', models.CharField(blank=True, choices=[('iron', 'Iron'), ('tile', 'Tile'), ('asbestos', 'Asbestos'), ('poly_sheeting', 'Poly Sheeting'), ('pressed_metal', 'Pressed Metal')], max_length=15)),
                ('pitch_of_roof', models.TextField(blank=True)),
                ('leak_present', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=5)),
                ('cause_of_leak_found', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=5)),
                ('leak_fixed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=5)),
                ('works_required', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roof_submission', to='reports.jobreport')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roof_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roof Report Submission',
            },
        ),
        migrations.CreateModel(
            name='SprayTestSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('attendance_datetime', models.DateTimeField()),
                ('property_construction', models.CharField(blank=True, choices=[('brick_veneer', 'Brick Veneer'), ('double_brick', 'Double Brick')], max_length=20)),
                ('discussion_with_insured', models.TextField(blank=True)),
                ('resultant_damage', models.TextField(blank=True)),
                ('testing_location', models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('ensuite', 'Ensuite'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('external_wall', 'External Wall'), ('balcony', 'Balcony'), ('window', 'Window'), ('door', 'Door'), ('roller_door', 'Roller Door'), ('other', 'Other')], max_length=15)),
                ('flood_test', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('flood_test_notes', models.TextField(blank=True)),
                ('spray_test', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=10)),
                ('spray_test_notes', models.TextField(blank=True)),
                ('tile_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('tile_condition_notes', models.TextField(blank=True)),
                ('grout_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('grout_condition_notes', models.TextField(blank=True)),
                ('silicone_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=10)),
                ('silicone_condition_notes', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spray_submission', to='reports.jobreport')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spray_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spray Test Submission',
            },
        ),
    ]
