# Generated by Django 5.2.11 on 2026-03-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle dedicated to this employee by admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee', to='fleets.vehicle'),
        ),
    ]
