# Generated by Django 5.2.11 on 2026-05-21 12:01

import django.db.models.deletion
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employeeprofile_assigned_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(help_text='Hex color code, e.g. #f54900', max_length=7, validators=[user.models.validate_hex_color])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_color', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Color',
                'verbose_name_plural': 'User Colors',
            },
        ),
    ]
