# Generated by Django 5.2.11 on 2026-04-30 18:23

import django.db.models.deletion
import fleets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_due',
            field=models.DateField(blank=True, help_text='Date when vehicle registration is due for renewal', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_due',
            field=models.DateField(blank=True, help_text='Date when next service is due', null=True),
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date fuel was added')),
                ('litres', models.DecimalField(decimal_places=2, help_text='Litres of fuel added', max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost of fuel', max_digits=8)),
                ('odometer_km', models.PositiveIntegerField(blank=True, help_text='Odometer reading at time of fill-up', null=True)),
                ('receipt_photo', models.ImageField(blank=True, help_text='Photo of the fuel receipt', null=True, upload_to=fleets.models.fuel_receipt_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleets.vehicle')),
            ],
            options={
                'verbose_name': 'Fuel Log',
                'verbose_name_plural': 'Fuel Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
