# Generated by Django 5.2.11 on 2026-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_vehicle_registration_due_vehicle_service_due_fuellog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of fuel', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='date',
            field=models.DateField(blank=True, help_text='Date fuel was added', null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Litres of fuel added', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
