# Generated by Django 5.2.11 on 2026-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('pass_changed', 'Password Changed'), ('job_assigned', 'Job Assigned'), ('job_updated', 'Job Updated'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_overdue', 'Job Overdue'), ('job_rescheduled', 'Job Rescheduled'), ('note_assigned', 'Note Assigned'), ('report_submitted', 'Report Submitted'), ('safety_form_submitted', 'Safety Form Submitted'), ('vehicle_issue_reported', 'Vehicle Issue Reported'), ('vehicle_inspection_due', 'Vehicle Inspection Due'), ('vehicle_service_overdue', 'Vehicle Service Overdue'), ('support_request', 'Support Request'), ('issue_report', 'Issue Report'), ('new_user', 'New User Joined')], max_length=50),
        ),
    ]
